package comparison.issues;

public enum IssueKind {
    CLASS_MISSING_IN_CODE,
    CLASS_MISSING_IN_UML,
    CLASS_MISMATCH,

    ATTRIBUTE_MISSING_IN_CODE,
    ATTRIBUTE_MISSING_IN_UML,
    ATTRIBUTE_MISMATCH,

    METHOD_MISSING_IN_CODE,
    METHOD_MISSING_IN_UML,
    METHOD_MISMATCH,

    RELATIONSHIP_MISSING_IN_CODE,
    RELATIONSHIP_MISSING_IN_UML,
    RELATIONSHIP_MISMATCH
}