@startuml
class CardGateway {
  + pay(double) : void
}
class Customer {
  - order : Order
  + setOrder(Order) : void
  + getOrder() : Order
}
class Order {
}
interface PaymentGateway {
  + pay(double amount) : void
}
PaymentGateway <|.. CardGateway
Customer o-- Order
@enduml
