@startuml
class CardGateway {
  + pay(amount : double) : void
}
class Customer {
  - order : Order
  + setOrder(order : Order) : void
  + getOrder() : Order
}
class Order {
}
interface PaymentGateway {
  + pay(amount : double) : void
}
PaymentGateway <|.. CardGateway
Customer o-- Order
@enduml
